# Generated by Django 2.1.5 on 2019-10-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20191010_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(max_length=120),
        ),
        migrations.AlterField(
            model_name='student',
            name='exam_grade',
            field=models.CharField(choices=[('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D+', 'D+'), ('D', 'D'), ('D-', 'D-'), ('E+', 'E+'), ('E', 'E'), ('E-', 'E-'), ('F', 'F')], max_length=105),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=120),
        ),
    ]
